apiVersion: v1
kind: Secret
metadata:
  name: fcg-payments-secret
type: Opaque
stringData:
    ConnectionStrings__DefaultConnection: "Host=fcgpayments-postgres-svc;Port=5432;Database=postgres;Username=postgres;Password=senha"
    RabbitMQ__Host: fcgpayments-rabbitmq-svc
    RabbitMQ__VirtualHost: "my_vhost"
    RabbitMQ__Username: user
    RabbitMQ__Password: senha