name: Pipeline Infra

on:
  push:
    branches:
      - main
    tags:
      - 'v*' 




jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        AWS_REGION: ${{vars.AWS_REGION}}
        CLUSTER_NAME: ${{vars.CLUSTER_NAME}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore FCGPayments.slnx

      - name: Build
        run: dotnet build FCGPayments.slnx --no-restore --configuration Release

      - name: Testar e gerar relatório
        run: dotnet test FCGPayments.slnx --no-build --configuration Release --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults
      

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{vars.AWS_REGION}}
      
      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, e push imagem docker no ECR
        if: startsWith(github.ref, 'refs/tags/') 
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{vars.AWS_REPOSITORY}}
          IMAGE_VERSION_TAG: ${{ github.ref_name }}
        run: |
          CLEAN_TAG=$(echo $IMAGE_VERSION_TAG| sed 's/^v//')
          docker build -t $REGISTRY/$REPOSITORY:$CLEAN_TAG .
          docker push $REGISTRY/$REPOSITORY:$CLEAN_TAG

      
      - name: Deploy no EKS
        if: startsWith(github.ref, 'refs/tags/')
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{vars.AWS_REPOSITORY}}
          IMAGE_VERSION_TAG: ${{ github.ref_name }}
          DEPLOYMENT_NAME: ${{vars.DEPLOYMENT_NAME}}
          CONTAINER_NAME: ${{vars.CONTAINER_NAME}}
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
          kubectl apply -f ./k8s/
          kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$REGISTRY/$REPOSITORY:$CLEAN_TAG
          kubectl rollout status deployment/$DEPLOYMENT_NAME

      - name: Publicando relatório de teste
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Relatório de Testes C#
          path: TestResults/test-results.trx
          reporter: dotnet-trx